### ISSUE TITLE
Wallet unable to display any information

### ISSUE THREAD

**Issue by talilosis** [ZephyrProtocol/zephyr#17]
![图片](https://github.com/ZephyrProtocol/zephyr/assets/50024543/024db441-e01d-4bf7-b19f-75a85917af26)
My wallet got stuck when I sent the coin on 12-5 noon, and it hasn't been sent out properly yet. My wallet balance has also disappeared, and I can't access history properly. I haven't received the target address, so I can't provide a transaction ID because my wallet can't see anything at the moment

**Comment by talilosis** [comment]
This is my wallet address：
ZEPHYR3HJB3G2hsHWd8VAvHESJKVHyqvj7ZRHnZKC6ayf7B9E8rk4z2MVXEF6UyypqLvtsUwHqMQwC7P8QigfgANSzbKwUdHGdv1H

**Comment by GreenHashn** [comment]
fixed mine < got to setting where it says update block put it at 0 hit update. then go to advanced top right corner hit resync wallet it took a very long time like 12 hrs  funds were there when i woke up

**Comment by talilosis** [comment]
Thanks, I'll try it.

**Comment by anhb** [comment]
I'm still having the same issue. I've tried restoring the wallet file, re-scan wallet and I'm still having the same issue, only showing zero balance and nothing else, every time I log in to the wallet web page, the "refresh height" is zero too. Could someone help me?
